### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by dioxide-orange** [Zirconium233/yunForNewVerison#8]
**在python main.py时老是显示**

Traceback (most recent call last):
  File "C:\Users\氧化橙\Downloads\yunForNewVerison-master\main.py", line 29, in <module>
    my_host = conf.get("Yun", "school_host") # 学校的host
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\configparser.py", line 759, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\configparser.py", line 1132, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Yun'

**实在没招了**

**Comment by Zirconium233** [comment]
这个报错写的很明显是config.ini没有键yun，看样子应该是config.ini压根不在工作目录，open新建了一个新的空config.ini，读取肯定是报错。建议cd到工作目录再python main.py

**Comment by dioxide-orange** [comment]
HTTPConnectionPool(host='127.0.0.1', port=2334): Max retries exceeded with url: http://210.45.246.53:8080/run/getHomeRunInfo (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002676AC55AF0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
这又发生了什么啊啊啊啊（本人纯菜鸡）

**Comment by dioxide-orange** [comment]
我焯，又跑起来了，谢谢大佬的代码
